build apps with engine provided frontend snapshot
meta-flutter/meta-flutter pull request #580
Opened 2024-10-10 09:32 UTC by andryblack

Resolve https://github.com/meta-flutter/meta-flutter/issues/575

2024-10-14 16:22 UTC, jwinarske requested changes
other than requested change LTGM

2024-10-14 16:22 UTC, jwinarske commented on conf/include/common.inc
>                  frontend_snapshot = f'{flutter_sdk}/bin/cache/artifacts/engine/linux-{clang_build_arch(d)}/frontend_server.dart.snapshot'
If we switch one, we should switch the other to use engine_sdk executables

2024-10-14 23:06 UTC, andryblack commented on conf/include/common.inc
>                  frontend_snapshot = f'{flutter_sdk}/bin/cache/artifacts/engine/linux-{clang_build_arch(d)}/frontend_server.dart.snapshot'
need more research, some executables builded for target machine. 
Im return to it at this week

2024-11-16 06:01 UTC, jwinarske commented on conf/include/common.inc
>                  frontend_snapshot = f'{flutter_sdk}/bin/cache/artifacts/engine/linux-{clang_build_arch(d)}/frontend_server.dart.snapshot'
@andryblack are you still planning on working on this?

2024-12-17 21:52 UTC, jwinarske commented
closing due to lack of response

2024-12-17 21:52 UTC, closed without merging